version: '3.8'
services:
  tomcat:
    image: tomcat:9.0
    container_name: tomcat9
    ports:
      - "8080:8080"
    volumes:
      - ./target/spring-legacy-app.war:/usr/local/tomcat/webapps/spring.war
    depends_on:
      - mysql
